// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWb7TMO0e_o4rHYExTr9le0kLwFS51kwM',
    appId: '1:879124293537:web:e0266b8dfed64580e98de0',
    messagingSenderId: '879124293537',
    projectId: 'dicoding-chatting-16421',
    authDomain: 'dicoding-chatting-16421.firebaseapp.com',
    storageBucket: 'dicoding-chatting-16421.firebasestorage.app',
    measurementId: 'G-JD9CGDMHC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDRDMYxSNcXJxlwRZBaLDjieLLbCSG5E',
    appId: '1:879124293537:android:365057c0a9460978e98de0',
    messagingSenderId: '879124293537',
    projectId: 'dicoding-chatting-16421',
    storageBucket: 'dicoding-chatting-16421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhMbGeRkUS42JnhTWXcPwlzyhGn4BA89s',
    appId: '1:879124293537:ios:3a67245b4047e3a2e98de0',
    messagingSenderId: '879124293537',
    projectId: 'dicoding-chatting-16421',
    storageBucket: 'dicoding-chatting-16421.firebasestorage.app',
    iosBundleId: 'com.dicoding.chattingApp',
  );
}
